import logging

SIMULATION_DURATION_SECONDS = 30
SIMULATION_SPEED_FACTOR = 1.0
LOG_LEVEL = logging.INFO
LOG_DIRECTORY = "simulation_logs"
LOG_FILENAME_PREFIX = "drone_sim"
RESULTS_DIRECTORY = "simulation_results"

NUM_GROUPS = 1
NUM_DRONES_PER_GROUP = 20

VOTING_THRESHOLD_PREPARES = 0.66
VOTING_THRESHOLD_CONSISTENCY_IN_PREPARES = 0.66

ABSOLUTE_POSITION_ERROR_THRESHOLD = 0.5
RELATIVE_POSITION_ERROR_THRESHOLD = 0.3

PROB_IS_INITIALLY_ABS_DEFECTIVE = 0.20
PROB_ABS_GETS_DEFECTIVE = 0.01
ABS_POS_ERROR_MAGNITUDE = 1.0

PROB_IS_INITIALLY_REL_DEFECTIVE = 0.20
PROB_REL_GETS_DEFECTIVE = 0.01
REL_POS_ERROR_MAGNITUDE = 0.8

PROB_DRONE_INITIATES_CONSENSUS = 0.5
PROB_LEADER_INITIATES_CONSENSUS_SELF = 0.05

CREDIT_SUCCESSFUL_PROPOSAL_VALIDATED = 2.0
CREDIT_REJECTED_PROPOSAL = -5.0
CREDIT_MANAGED_SUCCESSFUL_VALIDATION = 1.0
CREDIT_MANAGED_REJECTION = 0.5
CREDIT_PARTICIPATED_SUCCESSFUL_VALIDATION = 0.5
CREDIT_PARTICIPATED_REJECTION = 0.2
